# Generated by Django 4.2.9 on 2024-01-22 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='US', max_length=2)),
                ('iata', models.CharField(max_length=3)),
                ('icao', models.CharField(max_length=4)),
                ('airport', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_hours', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('private_pilot', models.BooleanField(default=False)),
                ('instrument_rating', models.BooleanField(default=False)),
                ('commercial_pilot_single_engine', models.BooleanField(default=False)),
                ('flight_instructor_cfi', models.BooleanField(default=False)),
                ('flight_instructor_cfii', models.BooleanField(default=False)),
                ('commercial_pilot_multi_engine', models.BooleanField(default=False)),
                ('flight_instructor_multi_engine_mei', models.BooleanField(default=False)),
                ('safety_pilot_need_vfr_single_engine', models.BooleanField(default=False)),
                ('safety_pilot_need_ifr_single_engine', models.BooleanField(default=False)),
                ('safety_pilot_need_ifr_multi_engine', models.BooleanField(default=False)),
                ('safety_pilot_offer_vfr_single_engine', models.BooleanField(default=False)),
                ('safety_pilot_offer_ifr_single_engine', models.BooleanField(default=False)),
                ('safety_pilot_offer_ifr_multi_engine', models.BooleanField(default=False)),
                ('instructor_need_cfi', models.BooleanField(default=False)),
                ('instructor_need_instrument_cfii', models.BooleanField(default=False)),
                ('instructor_need_commercial_single_engine', models.BooleanField(default=False)),
                ('instructor_need_commercial_multi_engine_mei', models.BooleanField(default=False)),
                ('instructor_offer_cfi', models.BooleanField(default=False)),
                ('instructor_offer_instrument_cfii', models.BooleanField(default=False)),
                ('instructor_offer_commercial_single_engine', models.BooleanField(default=False)),
                ('instructor_offer_commercial_multi_engine_mei', models.BooleanField(default=False)),
                ('rent_need_single_engine', models.BooleanField(default=False)),
                ('rent_need_multi_engine', models.BooleanField(default=False)),
                ('rent_offer_single_engine', models.BooleanField(default=False)),
                ('rent_offer_multi_engine', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('home_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connections.airportdata')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PilotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('event_start_date', models.DateField()),
                ('event_finish_date', models.DateField()),
                ('event_description', models.TextField()),
                ('host_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_airport_events', to='connections.airportdata')),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('second_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_airport_events', to='connections.airportdata')),
                ('third_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_airport_events', to='connections.airportdata')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deleted_for_user', models.ManyToManyField(blank=True, related_name='deleted_messages', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
