from django.urls import path
from . import views
from .views import (
    welcome,
    register,
    user_login,
    user_logout,
    home,
    update_pilot_profile,
    airport_list,
    airport_list_by_state,
    user_list,
    user_list_by_state,
    users_same_airport,
    view_pilot_profile,
    send_message,
    view_messages,
    send_reply,
    create_pilot_event,
    event_list,
    view_pilot_event,
    user_hosted_events,
    edit_pilot_event,
    delete_pilot_event,
    EventListByStateView,
    SafetyPilotListView,
    SafetyPilotListViewByState,
    SafetyPilotListByHomeAirportView,
    SafetyPilotListOfferingView,
    SafetyPilotListOfferingByStateView,
    SafetyPilotListOfferingByAirportView,
    InstructorListView,
    InstructorListViewByState,
    InstructorListByHomeAirportView,
    InstructorListOfferingView,
    InstructorListOfferingByStateView,
    InstructorListOfferingByHomeAirportView,

)



urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('home/', views.home, name='home'),
    path('update-profile/', views.update_pilot_profile, name='update_pilot_profile'),
    path('airport-list/', views.airport_list, name='airport_list'),
    path('airport-list-by-state/', views.airport_list_by_state, name='airport_list_by_state'),
    path('user-list/', views.user_list, name='user_list'),
    path('user-list-by-state/', views.user_list_by_state, name='user_list_by_state'),
    path('users-same-airport/', views.users_same_airport, name='users_same_airport'),
    path('view-profile/<int:user_id>/', views.view_pilot_profile, name='view_pilot_profile'),
    path('send-message/<int:recipient_id>/', views.send_message, name='send_message'),
    path('view-messages/', views.view_messages, name='view_messages'),
    path('send-reply/<int:message_id>/', views.send_reply, name='send_reply'),
    path('create-pilot-event/', views.create_pilot_event, name='create_pilot_event'),
    path('event-list/', views.event_list, name='event_list'),
    path('view-pilot-event/<str:event_name>/', views.view_pilot_event, name='view_pilot_event'),
    path('user-hosted-events/', views.user_hosted_events, name='user_hosted_events'),
    path('edit-pilot-event/<int:event_id>/', views.edit_pilot_event, name='edit_pilot_event'),
    path('delete_pilot_event/<int:event_id>/', views.delete_pilot_event, name='delete_pilot_event'),
    path('event_list_by_state/', EventListByStateView.as_view(), name='event_list_by_state'),
    path('safety-pilot-list/', SafetyPilotListView.as_view(), name='safety_pilot_list'),
    path('safety_pilot_list_by_state/', SafetyPilotListViewByState.as_view(), name='safety_pilot_list_by_state'),
    path('safety_pilot_list_by_home_airport/', SafetyPilotListByHomeAirportView.as_view(), name='safety_pilot_list_by_home_airport'),
    path('safety-pilot_list_offering/', SafetyPilotListOfferingView.as_view(), name='safety_pilot_list_offering'),
    path('safety_pilot_list_offering_by_state/', SafetyPilotListOfferingByStateView.as_view(), name='safety_pilot_list_offering_by_state'),
    path('safety_pilot_list_offering_by_airport/', SafetyPilotListOfferingByAirportView.as_view(), name='safety_pilot_list_offering_by_airport'),
    path('instructor-list/', views.InstructorListView.as_view(), name='instructor_list'),
    path('instructor_list_by_state/', views.InstructorListViewByState.as_view(), name='instructor_list_by_state'),
    path('instructor_list_by_home_airport/', views.InstructorListByHomeAirportView.as_view(), name='instructor_list_by_home_airport'),
    path('instructor_list_offering/', views.InstructorListOfferingView.as_view(), name='instructor_list_offering'),
    path('instructor_list_offering_by_state/', views.InstructorListOfferingByStateView.as_view(), name='instructor_list_offering_by_state'),
    path('instructor_list_offering_by_home_airport/', views.InstructorListOfferingByHomeAirportView.as_view(), name='instructor_list_offering_by_home_airport'),

]


